In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from google.colab import files
upload = files.upload()

Saving heartdisease.csv to heartdisease.csv

In [6]:
df = pd.read_csv('heartdisease.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
df.shape

(303, 14)

In [8]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [10]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [11]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [12]:
!pip install pgmpy==1.0.0
import pgmpy
print(pgmpy.__version__)

Collecting pgmpy==1.0.0
  Downloading pgmpy-1.0.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Collecting pyro-ppl (from pgmpy==1.0.0)
  Downloading pyro_ppl-1.9.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Collecting pyro-api>=0.1.1 (from pyro-ppl->pgmpy==1.0.0)
  Downloading pyro_api-0.1.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.3.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
Downloading pgmpy-1.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 47.1 MB/s eta 0:00:00
Downloading pyro_ppl-1.9.1-py3-none-any.whl (755 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 36.5 MB/s eta 0:00:00
Downloading pyro_api-0.1.2-py3-none-any.whl (11 kB)
Installing collected packages: pyro-api, pyro-ppl, pgmpy
Successfully installed pgmpy-1.0.0 pyro-api-0.1.2 pyro-ppl-1.9.1
1.0.0

In [24]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
model = DiscreteBayesianNetwork([
('age', 'target'),
('sex', 'target'),
('chol', 'target') ])
mle = MaximumLikelihoodEstimator(model, df)
cpds = mle.get_parameters()
model.add_cpds(*cpds)
print(model.get_cpds('target'))

+-----------+-----------+-----------+-----+-----------+-----------+
| age       | age(29)   | age(29)   | ... | age(77)   | age(77)   |
+-----------+-----------+-----------+-----+-----------+-----------+
| chol      | chol(126) | chol(126) | ... | chol(564) | chol(564) |
+-----------+-----------+-----------+-----+-----------+-----------+
| sex       | sex(0)    | sex(1)    | ... | sex(0)    | sex(1)    |
+-----------+-----------+-----------+-----+-----------+-----------+
| target(0) | 0.5       | 0.5       | ... | 0.5       | 0.5       |
+-----------+-----------+-----------+-----+-----------+-----------+
| target(1) | 0.5       | 0.5       | ... | 0.5       | 0.5       |
+-----------+-----------+-----------+-----+-----------+-----------+

In [25]:
print(model.get_cpds('age'))

+---------+------------+
| age(29) | 0.00330033 |
+---------+------------+
| age(34) | 0.00660066 |
+---------+------------+
| age(35) | 0.0132013  |
+---------+------------+
| age(37) | 0.00660066 |
+---------+------------+
| age(38) | 0.00990099 |
+---------+------------+
| age(39) | 0.0132013  |
+---------+------------+
| age(40) | 0.00990099 |
+---------+------------+
| age(41) | 0.0330033  |
+---------+------------+
| age(42) | 0.0264026  |
+---------+------------+
| age(43) | 0.0264026  |
+---------+------------+
| age(44) | 0.0363036  |
+---------+------------+
| age(45) | 0.0264026  |
+---------+------------+
| age(46) | 0.0231023  |
+---------+------------+
| age(47) | 0.0165017  |
+---------+------------+
| age(48) | 0.0231023  |
+---------+------------+
| age(49) | 0.0165017  |
+---------+------------+
| age(50) | 0.0231023  |
+---------+------------+
| age(51) | 0.039604   |
+---------+------------+
| age(52) | 0.0429043  |
+---------+------------+
| age(53) | 0.0264026  |
+---------+------------+
| age(54) | 0.0528053  |
+---------+------------+
| age(55) | 0.0264026  |
+---------+------------+
| age(56) | 0.0363036  |
+---------+------------+
| age(57) | 0.0561056  |
+---------+------------+
| age(58) | 0.0627063  |
+---------+------------+
| age(59) | 0.0462046  |
+---------+------------+
| age(60) | 0.0363036  |
+---------+------------+
| age(61) | 0.0264026  |
+---------+------------+
| age(62) | 0.0363036  |
+---------+------------+
| age(63) | 0.029703   |
+---------+------------+
| age(64) | 0.0330033  |
+---------+------------+
| age(65) | 0.0264026  |
+---------+------------+
| age(66) | 0.0231023  |
+---------+------------+
| age(67) | 0.029703   |
+---------+------------+
| age(68) | 0.0132013  |
+---------+------------+
| age(69) | 0.00990099 |
+---------+------------+
| age(70) | 0.0132013  |
+---------+------------+
| age(71) | 0.00990099 |
+---------+------------+
| age(74) | 0.00330033 |
+---------+------------+
| age(76) | 0.00330033 |
+---------+------------+
| age(77) | 0.00330033 |
+---------+------------+

In [26]:
print(model.get_cpds('sex'))

+--------+----------+
| sex(0) | 0.316832 |
+--------+----------+
| sex(1) | 0.683168 |
+--------+----------+

In [27]:
print(model.get_cpds('chol'))

+-----------+------------+
| chol(126) | 0.00330033 |
+-----------+------------+
| chol(131) | 0.00330033 |
+-----------+------------+
| chol(141) | 0.00330033 |
+-----------+------------+
| chol(149) | 0.00660066 |
+-----------+------------+
| chol(157) | 0.00330033 |
+-----------+------------+
| chol(160) | 0.00330033 |
+-----------+------------+
| chol(164) | 0.00330033 |
+-----------+------------+
| chol(166) | 0.00330033 |
+-----------+------------+
| chol(167) | 0.00330033 |
+-----------+------------+
| chol(168) | 0.00330033 |
+-----------+------------+
| chol(169) | 0.00330033 |
+-----------+------------+
| chol(172) | 0.00330033 |
+-----------+------------+
| chol(174) | 0.00330033 |
+-----------+------------+
| chol(175) | 0.00990099 |
+-----------+------------+
| chol(176) | 0.00330033 |
+-----------+------------+
| chol(177) | 0.0132013  |
+-----------+------------+
| chol(178) | 0.00330033 |
+-----------+------------+
| chol(180) | 0.00330033 |
+-----------+------------+
| chol(182) | 0.00330033 |
+-----------+------------+
| chol(183) | 0.00330033 |
+-----------+------------+
| chol(184) | 0.00330033 |
+-----------+------------+
| chol(185) | 0.00330033 |
+-----------+------------+
| chol(186) | 0.00330033 |
+-----------+------------+
| chol(187) | 0.00330033 |
+-----------+------------+
| chol(188) | 0.00660066 |
+-----------+------------+
| chol(192) | 0.00660066 |
+-----------+------------+
| chol(193) | 0.00660066 |
+-----------+------------+
| chol(195) | 0.00330033 |
+-----------+------------+
| chol(196) | 0.00660066 |
+-----------+------------+
| chol(197) | 0.019802   |
+-----------+------------+
| chol(198) | 0.00660066 |
+-----------+------------+
| chol(199) | 0.00990099 |
+-----------+------------+
| chol(200) | 0.00330033 |
+-----------+------------+
| chol(201) | 0.00990099 |
+-----------+------------+
| chol(203) | 0.00990099 |
+-----------+------------+
| chol(204) | 0.019802   |
+-----------+------------+
| chol(205) | 0.00660066 |
+-----------+------------+
| chol(206) | 0.00660066 |
+-----------+------------+
| chol(207) | 0.00660066 |
+-----------+------------+
| chol(208) | 0.00660066 |
+-----------+------------+
| chol(209) | 0.00660066 |
+-----------+------------+
| chol(210) | 0.00330033 |
+-----------+------------+
| chol(211) | 0.0132013  |
+-----------+------------+
| chol(212) | 0.0165017  |
+-----------+------------+
| chol(213) | 0.00660066 |
+-----------+------------+
| chol(214) | 0.00660066 |
+-----------+------------+
| chol(215) | 0.00330033 |
+-----------+------------+
| chol(216) | 0.00660066 |
+-----------+------------+
| chol(217) | 0.00330033 |
+-----------+------------+
| chol(218) | 0.00660066 |
+-----------+------------+
| chol(219) | 0.00990099 |
+-----------+------------+
| chol(220) | 0.00990099 |
+-----------+------------+
| chol(221) | 0.00660066 |
+-----------+------------+
| chol(222) | 0.00660066 |
+-----------+------------+
| chol(223) | 0.00990099 |
+-----------+------------+
| chol(224) | 0.00330033 |
+-----------+------------+
| chol(225) | 0.00660066 |
+-----------+------------+
| chol(226) | 0.0132013  |
+-----------+------------+
| chol(227) | 0.00660066 |
+-----------+------------+
| chol(228) | 0.00660066 |
+-----------+------------+
| chol(229) | 0.00990099 |
+-----------+------------+
| chol(230) | 0.00990099 |
+-----------+------------+
| chol(231) | 0.00990099 |
+-----------+------------+
| chol(232) | 0.00660066 |
+-----------+------------+
| chol(233) | 0.0132013  |
+-----------+------------+
| chol(234) | 0.019802   |
+-----------+------------+
| chol(235) | 0.00660066 |
+-----------+------------+
| chol(236) | 0.00990099 |
+-----------+------------+
| chol(237) | 0.00330033 |
+-----------+------------+
| chol(239) | 0.0132013  |
+-----------+------------+
| chol(240) | 0.0132013  |
+-----------+------------+
| chol(241) | 0.00330033 |
+-----------+------------+
| chol(242) | 0.00330033 |
+-----------+------------+
| chol(243) | 0.0132013  |
+-----------+------------+
| chol(244) | 0.00990099 |
+-----------+------------+
| chol(245) | 0.00990099 |
+-----------+------------+
| chol(246) | 0.00990099 |
+-----------+------------+
| chol(247) | 0.00660066 |
+-----------+------------+
| chol(248) | 0.00660066 |
+-----------+------------+
| chol(249) | 0.00990099 |
+-----------+------------+
| chol(250) | 0.00990099 |
+-----------+------------+
| chol(252) | 0.00330033 |
+-----------+------------+
| chol(253) | 0.00660066 |
+-----------+------------+
| chol(254) | 0.0165017  |
+-----------+------------+
| chol(255) | 0.00660066 |
+-----------+------------+
| chol(256) | 0.00990099 |
+-----------+------------+
| chol(257) | 0.00330033 |
+-----------+------------+
| chol(258) | 0.00990099 |
+-----------+------------+
| chol(259) | 0.00330033 |
+-----------+------------+
| chol(260) | 0.00660066 |
+-----------+------------+
| chol(261) | 0.00660066 |
+-----------+------------+
| chol(262) | 0.00330033 |
+-----------+------------+
| chol(263) | 0.00990099 |
+-----------+------------+
| chol(264) | 0.00660066 |
+-----------+------------+
| chol(265) | 0.00660066 |
+-----------+------------+
| chol(266) | 0.00660066 |
+-----------+------------+
| chol(267) | 0.00660066 |
+-----------+------------+
| chol(268) | 0.00660066 |
+-----------+------------+
| chol(269) | 0.0165017  |
+-----------+------------+
| chol(270) | 0.00660066 |
+-----------+------------+
| chol(271) | 0.00660066 |
+-----------+------------+
| chol(273) | 0.00660066 |
+-----------+------------+
| chol(274) | 0.00990099 |
+-----------+------------+
| chol(275) | 0.00660066 |
+-----------+------------+
| chol(276) | 0.00330033 |
+-----------+------------+
| chol(277) | 0.00660066 |
+-----------+------------+
| chol(278) | 0.00330033 |
+-----------+------------+
| chol(281) | 0.00330033 |
+-----------+------------+
| chol(282) | 0.0132013  |
+-----------+------------+
| chol(283) | 0.00990099 |
+-----------+------------+
| chol(284) | 0.00330033 |
+-----------+------------+
| chol(286) | 0.00660066 |
+-----------+------------+
| chol(288) | 0.00990099 |
+-----------+------------+
| chol(289) | 0.00660066 |
+-----------+------------+
| chol(290) | 0.00330033 |
+-----------+------------+
| chol(293) | 0.00330033 |
+-----------+------------+
| chol(294) | 0.00660066 |
+-----------+------------+
| chol(295) | 0.00660066 |
+-----------+------------+
| chol(298) | 0.00660066 |
+-----------+------------+
| chol(299) | 0.00660066 |
+-----------+------------+
| chol(300) | 0.00330033 |
+-----------+------------+
| chol(302) | 0.00660066 |
+-----------+------------+
| chol(303) | 0.00990099 |
+-----------+------------+
| chol(304) | 0.00660066 |
+-----------+------------+
| chol(305) | 0.00330033 |
+-----------+------------+
| chol(306) | 0.00330033 |
+-----------+------------+
| chol(307) | 0.00330033 |
+-----------+------------+
| chol(308) | 0.00660066 |
+-----------+------------+
| chol(309) | 0.00990099 |
+-----------+------------+
| chol(311) | 0.00330033 |
+-----------+------------+
| chol(313) | 0.00330033 |
+-----------+------------+
| chol(315) | 0.00660066 |
+-----------+------------+
| chol(318) | 0.00660066 |
+-----------+------------+
| chol(319) | 0.00330033 |
+-----------+------------+
| chol(321) | 0.00330033 |
+-----------+------------+
| chol(322) | 0.00330033 |
+-----------+------------+
| chol(325) | 0.00660066 |
+-----------+------------+
| chol(326) | 0.00330033 |
+-----------+------------+
| chol(327) | 0.00330033 |
+-----------+------------+
| chol(330) | 0.00660066 |
+-----------+------------+
| chol(335) | 0.00660066 |
+-----------+------------+
| chol(340) | 0.00330033 |
+-----------+------------+
| chol(341) | 0.00330033 |
+-----------+------------+
| chol(342) | 0.00330033 |
+-----------+------------+
| chol(353) | 0.00330033 |
+-----------+------------+
| chol(354) | 0.00330033 |
+-----------+------------+
| chol(360) | 0.00330033 |
+-----------+------------+
| chol(394) | 0.00330033 |
+-----------+------------+
| chol(407) | 0.00330033 |
+-----------+------------+
| chol(409) | 0.00330033 |
+-----------+------------+
| chol(417) | 0.00330033 |
+-----------+------------+
| chol(564) | 0.00330033 |
+-----------+------------+